#!/usr/bin/env sh

scrDir=$(dirname "$(realpath "$0")")
source "$scrDir"/globalcontrol_fixed
rofiConf="${confDir}/rofi/quickapps.rasi"

[[ $rofiScale =~ ^[0-9]+$ ]] || rofiScale=10
r_scale="configuration {font: \"Monocraft ${rofiScale}\";}"
r_override="window {height: 18em; width: 14em; border: ${hypr_width}px; border-radius: 0;} element {border-radius: 0;}"

shaderStatus=$(hyprshade current)
shaderList=$(ls "$confDir/hypr/shaders" | sed 's/\.[^.]*$//')

if [[ $shaderStatus == "" ]]; then
        # If no shader is active, offer "Toggle" as the first option
        selectedOption=$(echo -e "Enable\n$shaderList" | rofi -dmenu -theme-str "$r_override" -theme-str "$r_scale" -config "$rofiConf")
else
        # If a shader is active, offer "Disable" as the first option
        selectedOption=$(echo -e "Disable\n$shaderList" | rofi -dmenu -theme-str "$r_override" -theme-str "$r_scale" -config "$rofiConf")
fi

if [ "$selectedOption" = "" ]; then
        exit
fi

if [ "$selectedOption" = "Disable" ]; then
        hyprshade off # Disable the shader
elif [ "$selectedOption" = "Enable" ]; then
        # Enable the most recent shader (the last one from the list)
        last_shader=$(tail -n 1 "$confDir/hypr/shaders/.last_shader.txt")
        hyprshade on "$last_shader"
else
        # Enable the selected shader
        hyprshade on "$selectedOption"

        # Update the last used shader (for future "Toggle" option)
        echo "$selectedOption" >"$confDir/hypr/shaders/.last_shader.txt"
fi

shaderStatus=$(hyprshade current)
notify-send "Shader: $shaderStatus"
