#!/usr/bin/env sh

# Check release
if [ ! -f /etc/arch-release ]; then
        exit 0
fi

# source variables
scrDir=$(dirname "$(realpath "$0")")
source "$scrDir/globalcontrol.sh"
get_aurhlpr
export -f pkg_installed
fpk_exup="pkg_installed flatpak && flatpak update"

# Trigger upgrade
if [ "$1" == "up" ]; then
        trap 'pkill -RTMIN+20 waybar' EXIT
        command="
    fastfetch -c ~/.config/fastfetch/1.jsonc
    $0 upgrade
    ${aurhlpr} -Syu
    $fpk_exup
    read -n 1 -p 'Press any key to continue...'
    "
        kitty -o font_size=10 --title systemupdate sh -c "${command}"
fi

# Check for AUR updates
aur=$(${aurhlpr} -Qua | wc -l)
ofc=$(
        (while pgrep -x checkupdates >/dev/null; do sleep 1; done)
        checkupdates | wc -l
)

# Check for flatpak updates
if pkg_installed flatpak; then
        fpk=$(flatpak remote-ls --updates | wc -l)
        fpk_disp="\n󰏓 Flatpak $fpk"
else
        fpk=0
        fpk_disp=""
fi

# Calculate total available updates
upd=$((ofc + aur + fpk))

[ "${1}" == upgrade ] && printf "[Official] %-10s\n[AUR]      %-10s\n[Flatpak]  %-10s\n" "$ofc" "$aur" "$fpk" && exit

# Show tooltip
if [ $upd -eq 0 ]; then
        upd="🬁 🬁 🬁"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 10 ]; then
        upd="🬁 🬁 🬓"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 20 ]; then
        upd="🬁 🬓 🬑"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 30 ]; then
        upd="🬓 🬁 🬑"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 40 ]; then
        upd="🬖 🬓 🬁"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 50 ]; then
        upd="🮋 🬓 🬄"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 60 ]; then
        upd="🮋 🬑 🬖"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 70 ]; then
        upd="🮋 🬖 🬄"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 80 ]; then
        upd="🮋 🮋 🬄"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 90 ]; then
        upd="🮋 🮋 🬑"
        echo "{\"text\":\"$upd\"}"
elif [ $upd -lt 100 ]; then
        upd="🮋 🮋 🮋"
        echo "{\"text\":\"$upd\"}"
else
        upd="🮋 🮋 🮋 🮋"
        echo "{\"text\":\"$upd\"}"
fi
